(() => {
  'use strict';
  const KEY='bookloop-phone-sample-v1';
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const yuan=v=>(Number(v||0)/100).toFixed(2);
  const clone=v=>JSON.parse(JSON.stringify(v));
  const uid=()=>globalThis.crypto?.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(36).slice(2)}`;
  const clock=t=>new Date(t).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});
  const roleName=r=>r==='buyer'?'体验买家':'体验卖家';
  const other=r=>r==='buyer'?'seller':'buyer';
  const initialBooks=[
    {id:'book-1',title:'微积分 上册',topic:'微积分',category:'通用',price:1800,image:'assets/calculus.webp',owner:'seller',condition:'八成新，有少量铅笔笔记，无缺页。',handoff:'支持线下交付，时间和地点可先聊聊。',area:'中心城区',status:'ACTIVE',created:6},
    {id:'book-2',title:'基础物理 第一册',topic:'基础物理',category:'基础科学',price:2200,image:'assets/physics.webp',owner:'seller',condition:'九成新，封面完整，内页有少量标注。',handoff:'可在公共交付点见面，请提前约时间。',area:'中心城区',status:'ACTIVE',created:5},
    {id:'book-3',title:'线性代数',topic:'线性代数',category:'通用',price:1200,image:'assets/algebra.webp',owner:'seller',condition:'八成新，适合复习使用，没有缺页。',handoff:'双方协商交付地点，建议当面检查教材。',area:'周边城区',status:'ACTIVE',created:4},
    {id:'book-4',title:'C 语言程序设计',topic:'程序设计',category:'计算技术',price:2600,image:'assets/programming.webp',owner:'seller',condition:'九成新，代码练习页有铅笔批注。',handoff:'支持线下见面交付，晚上较方便。',area:'中心城区',status:'ACTIVE',created:3},
    {id:'book-5',title:'实用英语 综合教程',topic:'实用英语',category:'语言学习',price:1500,image:'assets/english.webp',owner:'seller',condition:'八成新，练习部分有填写，阅读页较干净。',handoff:'可在公共交付点交付。',area:'周边城区',status:'ACTIVE',created:2},
    {id:'book-6',title:'微积分 下册',topic:'微积分',category:'通用',price:1600,image:'assets/calculus2.webp',owner:'seller',condition:'八成新，少量笔记，无破损和缺页。',handoff:'上、下册可分别购买，先确认需要的版本。',area:'中心城区',status:'ACTIVE',created:1},
  ];
  function fresh(){return {role:'buyer',verified:{buyer:true,seller:true},books:clone(initialBooks),orders:[],conversations:[],notices:[],history:[],feedback:[],checks:[]};}
  let state;try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');state=saved&&Array.isArray(saved.books)&&Array.isArray(saved.orders)&&Array.isArray(saved.conversations)?saved:fresh();}catch{state=fresh();}
  let route={view:'home'},stack=[],query='',category='全部',sort='new',messageTab='chat',publishDraft={};
  const root=$('#app');
  const icons={book:'<path d="M3 5c4-1 6 0 9 2v14c-3-2-5-3-9-2zM21 5c-4-1-6 0-9 2v14c3-2 5-3 9-2z"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4.5 4.5"/>',plus:'<rect x="3" y="3" width="18" height="18" rx="5"/><path d="M12 7v10M7 12h10"/>',chat:'<path d="M4 4h16v12H9l-5 4z"/><path d="M8 9h8M8 12h5"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',back:'<path d="m14 5-7 7 7 7"/>',chevron:'<path d="m9 6 6 6-6 6"/>',notice:'<path d="M4 10v5h4l9 4V5l-9 5zM7 15l2 5"/>',shield:'<path d="M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6z"/><path d="m8 12 3 3 5-6"/>',order:'<rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 3h6v4H9zM9 11h6M9 15h6"/>',wallet:'<path d="M4 6h14a2 2 0 0 1 2 2v11H4zM4 6V3h12v3M15 11h5v5h-5z"/>',history:'<path d="M4 9V4M4 9h5"/><path d="M4 9a9 9 0 1 1-1 6M12 7v6l4 2"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',image:'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1"/><path d="m3 17 5-5 4 4 4-7 5 8"/>',check:'<path d="m5 12 4 4L19 6"/>'};
  const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.book}</svg>`;
  const book=id=>state.books.find(b=>b.id===id);
  const order=id=>state.orders.find(o=>o.id===id);
  const statusText={UNPAID:'待付款',PAID:'待交付',DELIVERED:'待收货',SETTLED:'已结算',CANCELLED:'已取消',REFUND_REQUESTED:'退款审核中',WAIT_RETURN:'待退书',REFUNDED:'已退款',ACTIVE:'在售',PENDING:'待上架审核',SOLD:'已售出',RESERVED:'已锁定'};
  function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{toast('记录暂未保存，请减少上传图片或重置样品。');}}
  function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600);}
  function go(view,id,extra={}){stack.push(route);route={view,id,...extra};window.history.pushState({demoRoute:{...route}},'', '#'+view+(id?'/'+encodeURIComponent(id):view==='orders'?'/'+route.side:''));render();window.scrollTo({top:0});}
  function back(){route=stack.pop()||{view:'home'};window.history.replaceState({demoRoute:{...route}},'', '#'+route.view+(route.id?'/'+encodeURIComponent(route.id):route.view==='orders'?'/'+route.side:''));render();window.scrollTo({top:0});}
  function tab(view){stack=[];route={view};window.history.pushState({demoRoute:{...route}},'', '#'+view);render();window.scrollTo({top:0});}
  function notify(recipient,title,body,orderId){state.notices.unshift({id:uid(),recipient,title,body,orderId,time:Date.now()});}
  function modal(title,body,buttons=[{label:'知道了'}],extra=''){
    const host=$('#modal-root');host.innerHTML=`<div class="modal-mask"><section class="modal-sheet" role="dialog" aria-modal="true" aria-label="${esc(title)}"><h2>${esc(title)}</h2><p>${esc(body)}</p>${extra}<div class="button-row">${buttons.map((b,i)=>`<button class="${b.primary?'primary':'secondary'}" data-modal-index="${i}">${esc(b.label)}</button>`).join('')}</div></section></div>`;
    const previous=document.activeElement;host.querySelectorAll('[data-modal-index]').forEach(el=>el.addEventListener('click',()=>{const b=buttons[Number(el.dataset.modalIndex)];if(b.validate&&!b.validate())return;const values=Object.fromEntries([...host.querySelectorAll('input,textarea,select')].map(x=>[x.name,x.type==='checkbox'?x.checked:x.value]));host.innerHTML='';previous?.focus?.();b.action?.(values);}));
    host.querySelector('input,textarea,button')?.focus({preventScroll:true});
  }
  function switchRole(){modal('选择体验身份','可以分别体验买家找书和卖家处理订单。这里只切换演示身份。',[{label:'体验买家',primary:state.role==='buyer',action:()=>{state.role='buyer';persist();tab('profile');}},{label:'体验卖家',primary:state.role==='seller',action:()=>{state.role='seller';persist();tab('profile');}}]);}
  function header(title){return `<header class="topbar">${title?`<div class="back-title"><button class="icon-button" data-action="back" aria-label="返回">${icon('back')}</button>${esc(title)}</div>`:`<div class="brand"><span class="brand-icon">${icon('book')}</span><div><strong>BookLoop</strong><small>二手教材交易</small></div></div>`}<button class="role-pill" data-action="role">${state.role==='buyer'?'买家体验':'卖家体验'}</button></header>`;}
  function bottomTabs(){const count=state.notices.filter(n=>n.recipient===state.role&&!n.read).length;return `<nav class="tabs" aria-label="主导航">${[['home','book','找教材'],['publish','plus','发布'],['messages','chat','消息'],['profile','user','我的']].map(([view,i,label])=>`<button class="tab ${route.view===view?'active':''}" data-action="tab" data-view="${view}">${icon(i)}<span>${label}${view==='messages'&&count?`<span class="badge">${count}</span>`:''}</span></button>`).join('')}</nav>`;}
  const note=text=>`<div class="sample-note">${icon('info')}<span>${esc(text)}</span></div>`;
  function cards(books){return `<div class="book-grid">${books.map(b=>`<button class="book" data-action="detail" data-id="${esc(b.id)}"><img class="book-cover" src="${esc(b.image)}" alt="${esc(b.title)}演示封面" loading="lazy">${b.status!=='ACTIVE'?`<span class="sold">${esc(statusText[b.status])}</span>`:''}<div class="book-body"><h3>${esc(b.title)}</h3><p class="meta">${esc(b.condition)}</p><div class="book-foot"><span class="price"><small>¥</small>${yuan(b.price)}</span><span class="tag">${esc(b.category)}</span></div></div></button>`).join('')}</div>`;}
  function home(){let books=state.books.filter(b=>b.status==='ACTIVE'&&(category==='全部'||b.category===category)&&(!query||`${b.title} ${b.topic}`.toLowerCase().includes(query.toLowerCase())));books.sort(sort==='price'?(a,b)=>a.price-b.price:(a,b)=>b.created-a.created);return `<div class="content"><div class="intro"><h1>好教材，继续读。</h1><p>找一本需要的课本，也让闲置教材找到新主人。</p></div>${note('手机交互样品 · 所有付款均为模拟')}<form class="search" id="search-form">${icon('search')}<input id="search-input" value="${esc(query)}" placeholder="搜索教材名称、主题" aria-label="搜索教材"><button type="submit">搜索</button></form><div class="chips">${['全部','通用','基础科学','计算技术','语言学习'].map(c=>`<button class="chip ${c===category?'active':''}" data-action="category" data-value="${c}">${c==='全部'?'全部教材':c}</button>`).join('')}</div><button class="announcement" data-action="announcement">${icon('notice')}<span>请先核对版本和成色，再约定线下交付</span></button><div class="section-head"><h2>${query?'搜索结果':'最新上架'}</h2><select id="sort" aria-label="教材排序"><option value="new" ${sort==='new'?'selected':''}>最新 · ${books.length} 本</option><option value="price" ${sort==='price'?'selected':''}>价格从低到高</option></select></div>${books.length?cards(books):empty('没有找到教材','换个书名或主题试试。')}<div class="end">一本教材，连接两位读者</div></div>`;}
  function empty(title,desc){return `<div class="empty">${icon('book')}<div>${esc(title)}</div><div>${esc(desc)}</div></div>`;}
  function detail(){const b=book(route.id);if(!b)return empty('教材暂不可用','返回首页查看其他教材。');const mine=b.owner===state.role;return `<div class="content"><div class="detail-cover"><img src="${esc(b.image)}" alt="${esc(b.title)}教材封面"></div><div class="card"><div class="section-head" style="margin:0"><span class="price" style="font-size:30px"><small>¥</small>${yuan(b.price)}</span><span class="tag">线下交付</span></div><h1 class="detail-title">${esc(b.title)}</h1><div class="tags"><span class="tag">${esc(b.category)}</span><span class="tag">${esc(b.topic)}</span><span class="tag">${esc(b.area)}</span></div><div class="divider"></div><h3>成色与笔记</h3><p>${esc(b.condition)}</p><h3 style="margin-top:23px">交付说明</h3><p>${esc(b.handoff)}</p></div><div class="card"><div class="seller"><div class="avatar">${mine?'我':'书'}</div><div><strong>${esc(roleName(b.owner))}</strong><small>身份已审核 · 演示账号</small></div></div><p>先聊聊版本、照片和交付时间。收到教材后检查，再确认收货。</p></div>${note('封面和商品均为演示数据，不是真实在售商品。')}</div><div class="detail-actions"><button class="secondary" data-action="chat" data-id="${esc(b.id)}">${mine?'查看咨询':'联系卖家'}</button><button class="primary" data-action="buy" data-id="${esc(b.id)}" ${mine||b.status!=='ACTIVE'?'disabled':''}>${mine?'自己发布的教材':b.status==='ACTIVE'?'立即购买':statusText[b.status]}</button></div>`;}
  function publish(){const d=publishDraft;return `<div class="content"><div class="intro"><h1>让教材继续流转</h1><p>补全真实情况，帮助下一位读者选对教材。</p></div>${note('发布到此手机的样品记录中，其他人不会看到。')}<form id="publish-form" class="card"><label class="label">正反面照片</label><div class="photo-grid">${['front','back'].map((side,i)=>`<label class="photo-upload">${d[side]?`<img src="${esc(d[side])}" alt="教材${i?'反面':'正面'}照片">`:`${icon('image')}<span>${i?'反面照片':'正面照片'}</span>`}<input type="file" accept="image/*" data-photo="${side}" aria-label="选择教材${i?'反面':'正面'}照片"></label>`).join('')}</div><div class="upload-message">选择的图片仅用于本次样品体验。</div><label class="label" for="pub-title">教材名称</label><input class="field" id="pub-title" name="title" value="${esc(d.title)}" maxlength="100" placeholder="书名、版本或册次" required><label class="label" for="pub-topic">教材主题</label><input class="field" id="pub-topic" name="topic" value="${esc(d.topic)}" maxlength="50" placeholder="例如：微积分、程序设计" required><label class="label" for="pub-category">教材分类</label><select class="field" id="pub-category" name="category">${['通用','基础科学','计算技术','语言学习'].map(c=>`<option ${d.category===c?'selected':''}>${c}</option>`).join('')}</select><label class="label" for="pub-price">售价 元</label><input class="field" id="pub-price" name="price" type="number" inputmode="decimal" min="0.01" max="10000" step="0.01" value="${esc(d.price)}" placeholder="例如 18.00" required><p class="form-note">试运营手续费 0 元。样品不收款，也不会真实转账。</p><label class="label" for="pub-condition">成色与笔记</label><textarea class="field" id="pub-condition" name="condition" maxlength="300" placeholder="描述磨损、笔记、缺页等情况" required>${esc(d.condition)}</textarea><label class="label" for="pub-handoff">交付说明</label><textarea class="field" id="pub-handoff" name="handoff" maxlength="300" placeholder="说明地点和时间，不要公开详细住址" required>${esc(d.handoff)}</textarea><label class="confirm-check"><input type="checkbox" required>我确认这是演示发布，不涉及真实交易</label><button class="primary" type="submit">提交上架审核</button></form></div>`;}
  function profile(){const buys=state.orders.filter(o=>o.buyer===state.role),sales=state.books.filter(b=>b.owner===state.role);return `<div class="content"><div class="profile-head"><div class="avatar">${state.role==='buyer'?'买':'卖'}</div><div><h1>${roleName(state.role)}</h1><small>已认证的演示身份 · 可切换体验</small></div></div><button class="secondary" data-action="role">切换买家／卖家身份</button><div class="card stats-inline"><button data-action="orders" data-side="buyer"><strong>${buys.length}</strong>我的购买</button><button data-action="sales"><strong>${sales.length}</strong>我的发布</button><button data-action="funds"><strong>${yuan(funds().pending)}</strong>待结算 元</button></div><div class="card profile-menu">${[['orders','order','我的购买','buyer'],['sales','book','我的售卖',''],['orders','order','售卖订单','seller'],['funds','wallet','资金记录',''],['history','history','浏览记录',''],['verify','shield','身份认证',''],['guide','info','样品说明与反馈','']].map(([action,i,label,side])=>`<button class="menu-row" data-action="${action}" data-side="${side}"><span>${icon(i)}${label}</span>${icon('chevron','chevron')}</button>`).join('')}</div>${note('交易、审核、聊天和资金均为演示，不会产生真实费用。')}<button class="small-link reset-link" data-action="reset">重置本机的样品记录</button></div>`;}
  function ordersView(){const side=route.side||'buyer',items=state.orders.filter(o=>o[side]===state.role).sort((a,b)=>b.created-a.created);return `<div class="content"><h1 class="section-heading">${side==='seller'?'售卖订单':'我的购买'}</h1><p class="form-note">跟进付款、交付、收货和售后。</p>${items.length?items.map(o=>`<button class="card order-card" data-action="order" data-id="${o.id}"><div class="order-meta"><span>${new Date(o.created).toLocaleDateString('zh-CN')}</span><span class="tag">${statusText[o.status]}</span></div><div class="order-row"><img src="${esc(o.snapshot.image)}" alt="${esc(o.snapshot.title)}"><div class="info"><h3>${esc(o.snapshot.title)}</h3><span class="price"><small>¥</small>${yuan(o.amount)}</span></div>${icon('chevron','chevron')}</div></button>`).join(''):empty('还没有订单','在教材详情点击“立即购买”，体验一笔模拟交易。')}</div>`;}
  function orderView(){const o=order(route.id);if(!o)return empty('订单不存在','请返回订单列表。');const buyer=o.buyer===state.role,seller=o.seller===state.role;const desc={UNPAID:'15 分钟内完成模拟付款，或取消订单。',PAID:'等待卖家交付。付款后 72 小时未交付应自动退款。',DELIVERED:'收到教材并检查后确认收货；也可以申请整单退款。',SETTLED:'模拟结算已完成。后续争议可通过投诉协调。',REFUND_REQUESTED:'模拟审核中，结算暂停。可继续体验退款处理。',WAIT_RETURN:'退款已批准，需卖家确认退书后完成退款。',REFUNDED:'模拟退款已完成，没有发生真实资金退回。',CANCELLED:'订单已取消，教材重新可购买。'};return `<div class="content"><div class="card status-card"><h1>${statusText[o.status]}</h1><p>${desc[o.status]||''}</p><span class="tag warn">模拟订单，不涉及真实资金</span></div><div class="card"><div class="order-row"><img src="${esc(o.snapshot.image)}" alt="教材封面"><div class="info"><h3>${esc(o.snapshot.title)}</h3><span class="price"><small>¥</small>${yuan(o.amount)}</span></div></div><div class="divider"></div><div class="data-row"><span>订单编号</span><strong>${esc(o.number)}</strong></div><div class="data-row"><span>创建时间</span><strong>${clock(o.created)}</strong></div><div class="data-row"><span>成交价格</span><strong>¥${yuan(o.amount)}</strong></div><div class="data-row"><span>平台手续费</span><strong>0 元</strong></div><div class="data-row"><span>当前体验身份</span><strong>${roleName(state.role)}</strong></div></div><div class="button-row">${buyer&&o.status==='UNPAID'?`<button class="secondary" data-action="cancel" data-id="${o.id}">取消订单</button><button class="primary" data-action="pay" data-id="${o.id}">模拟付款</button>`:''}${seller&&o.status==='PAID'?`<button class="primary" data-action="deliver" data-id="${o.id}">标记已交付</button>`:''}${buyer&&o.status==='DELIVERED'?`<button class="primary" data-action="confirm" data-id="${o.id}">确认收货</button>`:''}${seller&&o.status==='WAIT_RETURN'?`<button class="primary" data-action="returned" data-id="${o.id}">确认退书并退款</button>`:''}</div>${buyer&&['PAID','DELIVERED'].includes(o.status)?`<div class="card"><h3>遇到交易问题？</h3><p>结算前可申请整单退款，说明未收到、版本不符等具体原因。</p><button class="secondary" data-action="refund" data-id="${o.id}">申请全额退款</button></div>`:''}${o.refund?`<div class="card"><h3>退款进度</h3><p>${esc(o.refund.reason)}</p><span class="tag">${esc(o.refund.result||'等待审核')}</span>${o.status==='REFUND_REQUESTED'?`<div class="button-row"><button class="secondary" data-action="review-refund" data-id="${o.id}" data-return="yes">模拟先退书</button><button class="primary" data-action="review-refund" data-id="${o.id}" data-return="no">模拟直接退款</button></div>`:''}</div>`:''}<div class="button-row"><button class="secondary" data-action="order-chat" data-id="${o.id}">联系交易对方</button><button class="secondary" data-action="complaint" data-id="${o.id}">投诉与协调</button></div>${(buyer&&o.status==='PAID')||(seller&&o.status==='DELIVERED')?`<p class="form-note">切换为${buyer?'卖家':'买家'}，可以继续体验${buyer?'标记交付':'确认收货'}。</p><button class="small-link" data-action="role">切换体验身份</button>`:''}</div>`;}
  function messages(){const convs=state.conversations.filter(c=>c.participants.includes(state.role));const notices=state.notices.filter(n=>n.recipient===state.role);return `<div class="content"><h1 class="section-heading">消息</h1><p class="form-note">沟通教材细节，跟进每一次交易。</p><div class="segmented"><button class="${messageTab==='chat'?'active':''}" data-action="message-tab" data-value="chat">教材聊天</button><button class="${messageTab==='notice'?'active':''}" data-action="message-tab" data-value="notice">交易通知</button></div>${messageTab==='chat'?convs.length?`<div class="card" style="padding:0 18px">${convs.map(c=>{const b=book(c.bookId),last=c.messages[c.messages.length-1];return `<button class="chat-list" data-action="open-chat" data-id="${c.id}"><div class="avatar">书</div><div class="chat-info"><div class="chat-header-meta"><strong>${roleName(c.participants.find(p=>p!==state.role))}</strong><small>${last?clock(last.time):''}</small></div><div class="chat-topic">${esc(b?.title||'教材咨询')}</div><p>${esc(last?.text||'开始聊聊这本教材')}</p></div></button>`}).join('')}</div>`:empty('还没有会话','在教材详情中点击“联系卖家”。'):notices.length?`<div class="card">${notices.map(n=>`<div class="notice-item"><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p><small>${clock(n.time)}</small>${n.orderId?`<button class="small-link" data-action="order" data-id="${n.orderId}">查看订单</button>`:''}</div>`).join('')}</div>`:empty('暂无交易通知','完成一次模拟付款，查看订单提醒。')}</div>`;}
  function chatView(){const c=state.conversations.find(c=>c.id===route.id);if(!c)return empty('暂无会话','从教材详情重新开始聊天。');const b=book(c.bookId);return `<div class="chat-view"><div class="chat-tip">${esc(b?.title)} · 演示对话会自动回复</div>${c.messages.map(m=>`<div class="message ${m.from===state.role?'mine':''}"><div class="stamp">${clock(m.time)}</div><div class="bubble">${m.image?`<img class="chat-image" src="${esc(m.image)}" alt="聊天图片" data-action="preview-photo" data-id="${esc(m.id)}">`:esc(m.text)}</div></div>`).join('')}<div id="chat-bottom"></div></div><div class="composer"><div class="compose-tools"><button data-action="chat-card" data-id="${c.id}">${icon('book')} 教材卡片</button><button data-action="chat-photo" data-id="${c.id}">${icon('image')} 图片</button></div><input type="file" id="chat-photo-input" accept="image/*" hidden><form class="compose-line" id="chat-form"><input id="chat-text" aria-label="聊天内容" placeholder="问问版本、笔记或交付时间…" maxlength="500" autocomplete="off" required><button class="primary">发送</button></form></div>`;}
  function sales(){const items=state.books.filter(b=>b.owner===state.role);return `<div class="content"><h1 class="section-heading">我的售卖</h1><p class="form-note">修改售价只影响后续订单，已下单价格保持不变。</p>${items.length?items.map(b=>`<div class="card"><div class="order-row"><img src="${esc(b.image)}" alt="教材封面"><div class="info"><h3>${esc(b.title)}</h3><span class="price">¥${yuan(b.price)}</span><span class="tag" style="margin-left:9px">${statusText[b.status]}</span></div></div><div class="button-row">${b.status==='PENDING'?`<button class="primary" data-action="approve-product" data-id="${b.id}">模拟审核通过</button>`:''}${b.status!=='SOLD'?`<button class="secondary" data-action="price" data-id="${b.id}">修改售价</button>`:''}<button class="secondary" data-action="detail" data-id="${b.id}">查看教材</button></div></div>`).join(''):empty('你还没有发布教材','在“发布”页上传一份演示教材。')}</div>`;}
  function funds(){const items=state.orders.filter(o=>o.seller===state.role);return {pending:items.filter(o=>['PAID','DELIVERED','REFUND_REQUESTED','WAIT_RETURN'].includes(o.status)).reduce((sum,o)=>sum+o.amount,0),settled:items.filter(o=>o.status==='SETTLED').reduce((sum,o)=>sum+o.amount,0),items:items.filter(o=>!['UNPAID','CANCELLED'].includes(o.status))};}
  function fundsView(){const f=funds();return `<div class="content"><h1 class="section-heading">资金记录</h1>${note('仅显示模拟金额，不是微信零钱或可提现余额。')}<div class="card money-card"><span class="tag">待结算</span><div class="balance">¥${yuan(f.pending)}</div><div class="divider"></div><div class="money-stats"><div>处理中<strong>¥0.00</strong></div><div>已结算<strong>¥${yuan(f.settled)}</strong></div></div></div><p class="form-note">买家确认收货后结算；未确认且已交付、无退款或纠纷的订单，按付款满 7 天检查结算条件。</p><div class="section-head"><h2>资金明细</h2><small>卖家记录</small></div>${f.items.length?f.items.map(o=>`<button class="card order-card" data-action="order" data-id="${o.id}"><div class="data-row"><span>${esc(o.snapshot.title)}</span><strong>¥${yuan(o.amount)}</strong></div><span class="tag">${statusText[o.status]}</span></button>`).join(''):empty('暂无资金记录','切换为卖家，并完成一笔模拟交易。')}</div>`;}
  function history(){const items=state.history.filter(h=>h.role===state.role).map(h=>book(h.id)).filter(Boolean);return `<div class="content"><h1 class="section-heading">浏览记录</h1><p class="form-note">最近看过的教材，方便再找到。</p>${items.length?cards(items):empty('暂无浏览记录','打开一本教材详情后再来看看。')}</div>`;}
  function verify(){return `<div class="content"><h1 class="section-heading">身份认证</h1><div class="card"><div class="seller"><div class="avatar">${icon('shield')}</div><div><strong>${state.verified[state.role]?'演示身份已通过':'等待演示认证'}</strong><small>样品不收集真实身份材料</small></div></div><p>正式产品中由管理员审核用户提交的认证材料，审核完成 7 天后删除原始图片。这里可以体验认证结果，无需上传身份证件。</p><button class="secondary" data-action="verify-demo">模拟认证通过</button></div></div>`;}
  function guide(){return `<div class="content"><h1 class="section-heading">样品说明与反馈</h1>${note('这是手机网页交互样品，原生微信小程序工程另附。')}<div class="card guide-text"><h2 style="margin-top:0">先试这几件事</h2>${['搜索和筛选一本教材，查看版本与成色','联系卖家，发送一条咨询消息','下单并模拟付款，切换卖家标记交付','切回买家确认收货，查看卖家资金记录','再试一笔退款，看看审核和退书流程','发布教材，模拟审核后回到首页查看'].map((t,i)=>`<label class="check"><input type="checkbox" data-check="${i}" ${state.checks?.includes(i)?'checked':''}><span>${t}</span></label>`).join('')}<h2>样品范围</h2><p>没有真实支付、真实审核员或真人聊天。数据仅保存在当前浏览器，换设备后不会同步。封面是演示图。主要用于判断页面、操作步骤和交易规则是否符合预期。</p><a class="download-link" href="./BookLoop_样品需求说明.pdf" target="_blank" rel="noopener">打开样品需求说明 PDF</a><button class="primary" data-action="feedback">记录体验反馈</button>${state.feedback.length?`<p>此浏览器已保存 ${state.feedback.length} 条反馈。</p>`:''}<button class="small-link" data-action="export-feedback">复制反馈给朋友</button></div></div>`;}
  function render(){const isTab=['home','publish','messages','profile'].includes(route.view),titles={detail:'教材详情',orders:'交易订单',order:'订单详情',chat:'教材聊天',sales:'我的售卖',funds:'资金记录',history:'浏览记录',verify:'身份认证',guide:'样品说明'};const views={home,publish,profile,detail,orders:ordersView,order:orderView,messages,chat:chatView,sales,funds:fundsView,history,verify,guide};root.innerHTML=`<main class="app-shell">${header(isTab?null:titles[route.view]||'BookLoop')}${(views[route.view]||home)()}${isTab?bottomTabs():''}</main>`;bindForms();if(route.view==='chat')setTimeout(()=>$('#chat-bottom')?.scrollIntoView({block:'end'}),40);}
  function startChat(id,allowOwner=false){const b=book(id);if(!b)return;if(b.owner===state.role&&!allowOwner){const existing=state.conversations.find(c=>c.bookId===id);if(existing){go('chat',existing.id);return;}toast('这是你的教材，先切换身份体验买家咨询。');return;}let c=state.conversations.find(c=>c.bookId===id&&c.participants.includes(state.role));if(!c){c={id:uid(),bookId:id,participants:[state.role,other(state.role)],messages:[{from:other(state.role),text:'你好，教材还在。版本、笔记和交付时间都可以先确认。',time:Date.now()}]};state.conversations.push(c);persist();}go('chat',c.id);}
  function changeOrder(id,required,next,action){const o=order(id);if(!o||!required.includes(o.status)){toast('订单状态已变化，请刷新查看。');render();return;}o.status=next;action?.(o);persist();render();}
  function captureDraft(){const form=$('#publish-form');if(form)Object.assign(publishDraft,Object.fromEntries(new FormData(form)));}
  function bindForms(){
    $('#search-form')?.addEventListener('submit',e=>{e.preventDefault();query=$('#search-input').value.trim();render();});
    $('#sort')?.addEventListener('change',e=>{sort=e.target.value;render();});
    $('#publish-form')?.addEventListener('input',captureDraft);
    root.querySelectorAll('[data-photo]').forEach(input=>input.addEventListener('change',async()=>{const file=input.files[0];if(!file)return;if(!file.type.startsWith('image/')||file.size>5*1024*1024){toast('请选择 5MB 以内的图片。');input.value='';return;}captureDraft();try{publishDraft[input.dataset.photo]=await readPhoto(file);render();}catch{toast('图片无法读取，请换一张。');}}));
    $('#publish-form')?.addEventListener('submit',e=>{e.preventDefault();captureDraft();if(!publishDraft.front||!publishDraft.back){toast('请分别选择正面和反面照片。');return;}const value=Number(publishDraft.price);if(!Number.isFinite(value)||value<=0||value>10000){toast('请输入有效价格。');return;}state.books.unshift({id:uid(),title:publishDraft.title.trim(),topic:publishDraft.topic.trim(),category:publishDraft.category||'通用',price:Math.round(value*100),image:publishDraft.front,backImage:publishDraft.back,owner:state.role,condition:publishDraft.condition.trim(),handoff:publishDraft.handoff.trim(),area:'约定地点',status:'PENDING',created:Date.now()});publishDraft={};persist();go('sales');toast('已提交演示审核，可点击模拟审核通过。');});
    $('#chat-photo-input')?.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(!file.type.startsWith('image/')||file.size>5*1024*1024){toast('请选择 5MB 以内的图片。');return;}try{const image=await readPhoto(file);const c=state.conversations.find(x=>x.id===route.id);c.messages.push({id:uid(),from:state.role,text:'[图片]',image,time:Date.now()});persist();render();}catch{toast('图片无法读取，请换一张。');}});
    $('#chat-form')?.addEventListener('submit',e=>{e.preventDefault();const text=$('#chat-text').value.trim();if(!text)return;const c=state.conversations.find(x=>x.id===route.id);c.messages.push({from:state.role,text,time:Date.now()});persist();render();const peer=other(state.role);setTimeout(()=>{c.messages.push({from:peer,text:text.includes('版本')?'演示教材的版本可以在详情页核对。正式交易前也建议双方再确认一次。':text.includes('笔记')?'有少量铅笔笔记，没有缺页。你可以先看照片，交付时再检查。':'可以，我们先确认教材版本，再协商方便的交付时间和地点。',time:Date.now()});persist();if(route.view==='chat'&&route.id===c.id)render();},750);});
    root.querySelectorAll('[data-check]').forEach(input=>input.addEventListener('change',()=>{const value=Number(input.dataset.check);state.checks=state.checks.filter(x=>x!==value);if(input.checked)state.checks.push(value);persist();}));
  }
  function readPhoto(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const scale=Math.min(1,900/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.8));};img.src=reader.result;};reader.readAsDataURL(file);});}
  const actions={
    tab:el=>tab(el.dataset.view),back,role:switchRole,category:el=>{category=el.dataset.value;render();},
    detail:el=>{const id=el.dataset.id;state.history=state.history.filter(h=>h.id!==id||h.role!==state.role);state.history.unshift({id,role:state.role});state.history=state.history.slice(0,80);persist();go('detail',id);},
    announcement:()=>modal('交易小提示','请核对书名、版本、笔记和缺页情况。双方协商线下交付，收到并检查后再确认收货。样品中的书籍与资金都是演示数据。'),
    chat:el=>startChat(el.dataset.id), 'open-chat':el=>go('chat',el.dataset.id),
    buy:el=>{const b=book(el.dataset.id);if(!b||b.owner===state.role||b.status!=='ACTIVE'){toast('这本教材暂不可购买。');return;}modal('创建模拟订单',`成交价 ¥${yuan(b.price)}。下单后锁定教材与价格，所有支付均为模拟。`,[{label:'再看看'},{label:'确认下单',primary:true,action:()=>{if(b.status!=='ACTIVE'){toast('教材已锁定。');return;}const o={id:uid(),number:`BL${Date.now().toString().slice(-10)}`,bookId:b.id,snapshot:clone(b),buyer:state.role,seller:b.owner,amount:b.price,status:'UNPAID',created:Date.now()};b.status='RESERVED';state.orders.unshift(o);persist();go('order',o.id);}}]);},
    orders:el=>go('orders',undefined,{side:el.dataset.side||'buyer'}),order:el=>go('order',el.dataset.id),sales:()=>go('sales'),funds:()=>go('funds'),history:()=>go('history'),verify:()=>go('verify'),guide:()=>go('guide'),
    cancel:el=>modal('取消订单','确认取消这笔未付款订单？',[{label:'保留订单'},{label:'确认取消',primary:true,action:()=>changeOrder(el.dataset.id,['UNPAID'],'CANCELLED',o=>{book(o.bookId).status='ACTIVE';})}]),
    pay:el=>{const o=order(el.dataset.id);modal('模拟付款',`体验支付 ¥${yuan(o.amount)}，不会调用真实微信支付或扣款。`,[{label:'暂不付款'},{label:'完成模拟付款',primary:true,action:()=>changeOrder(o.id,['UNPAID'],'PAID',o=>{o.paid=Date.now();book(o.bookId).status='SOLD';notify(o.seller,'教材已付款','请联系买家，约定交付时间和地点。',o.id);notify(o.buyer,'模拟付款成功','请与卖家约定线下交付。',o.id);toast('模拟付款成功。');})}]);},
    deliver:el=>modal('确认教材已交付','正式交易中，请完成实际交付后再标记。此处仅演示。',[{label:'暂不标记'},{label:'标记已交付',primary:true,action:()=>changeOrder(el.dataset.id,['PAID'],'DELIVERED',o=>{o.delivered=Date.now();notify(o.buyer,'卖家已标记交付','检查教材后确认收货，如有问题请申请退款。',o.id);})}]),
    confirm:el=>modal('确认收货','演示已收到教材并核对版本与成色，随后进入模拟结算。',[{label:'继续检查'},{label:'确认并模拟结算',primary:true,action:()=>changeOrder(el.dataset.id,['DELIVERED'],'SETTLED',o=>{notify(o.seller,'模拟结算完成','可以在资金记录中查看已结算金额。',o.id);toast('模拟结算完成。');})}]),
    'order-chat':el=>{const o=order(el.dataset.id);startChat(o.bookId,true);},
    refund:el=>modal('申请整单退款','说明问题。提交后暂停结算，可体验审核和退书。',[{label:'取消'},{label:'提交申请',primary:true,validate:()=>{if(!$('#refund-reason').value.trim()){toast('请填写退款原因。');return false;}return true;},action:v=>changeOrder(el.dataset.id,['PAID','DELIVERED'],'REFUND_REQUESTED',o=>{o.refund={reason:v.reason,result:'待审核'};notify(o.seller,'买家申请退款',v.reason,o.id);})}],'<textarea class="field" id="refund-reason" name="reason" maxlength="300" placeholder="例如：版本不符、未收到教材"></textarea>'),
    'review-refund':el=>changeOrder(el.dataset.id,['REFUND_REQUESTED'],el.dataset.return==='yes'?'WAIT_RETURN':'REFUNDED',o=>{o.refund.result=el.dataset.return==='yes'?'审核通过，等待退书':'全额模拟退款完成';if(o.status==='REFUNDED')book(o.bookId).status='PENDING';notify(o.buyer,'退款审核结果',o.refund.result,o.id);}),
    returned:el=>changeOrder(el.dataset.id,['WAIT_RETURN'],'REFUNDED',o=>{o.refund.result='已确认退书，全额模拟退款完成';book(o.bookId).status='PENDING';}),
    'message-tab':el=>{messageTab=el.dataset.value;state.notices.filter(n=>n.recipient===state.role).forEach(n=>n.read=true);persist();render();},
    'approve-product':el=>{const b=book(el.dataset.id);b.status='ACTIVE';persist();render();toast('演示审核通过，首页可以找到这本教材。');},
    price:el=>{const b=book(el.dataset.id);modal('修改售价','新价格只影响后续订单，已创建订单的价格保持不变。',[{label:'取消'},{label:'保存价格',primary:true,validate:()=>{const n=Number($('#new-price').value);if(!Number.isFinite(n)||n<=0||n>10000){toast('请输入有效价格。');return false;}return true;},action:v=>{b.price=Math.round(Number(v.price)*100);persist();render();toast('售价已更新。');}}],`<input class="field" id="new-price" name="price" type="number" inputmode="decimal" value="${yuan(b.price)}" min="0.01" step="0.01" aria-label="新价格 元">`);},
    'verify-demo':()=>{state.verified[state.role]=true;persist();render();toast('模拟认证通过。');},
    'chat-card':el=>{const c=state.conversations.find(x=>x.id===el.dataset.id);c.messages.push({from:state.role,text:`[教材卡片] ${book(c.bookId).title} · ¥${yuan(book(c.bookId).price)}`,time:Date.now()});persist();render();},
    'chat-photo':()=>$('#chat-photo-input')?.click(),
    'preview-photo':el=>{const c=state.conversations.find(c=>c.id===route.id);const image=c?.messages.find(m=>m.id===el.dataset.id)?.image;if(image)modal('聊天图片','图片仅用于本机样品体验。',[{label:'关闭'}],`<img class="photo-full" src="${esc(image)}" alt="聊天图片">`);},
    complaint:el=>modal('投诉与协调','记录问题，样品将展示提交结果，不会联系真实客服。',[{label:'取消'},{label:'提交演示投诉',primary:true,action:v=>{notify(state.role,'投诉已记录',v.content||'希望协助核实教材与交付情况。',el.dataset.id);persist();toast('演示投诉已记录，可到交易通知查看。');}}],'<textarea class="field" name="content" maxlength="300" placeholder="描述问题与希望的处理方式"></textarea>'),
    feedback:()=>modal('记录体验反馈','反馈只保存到此浏览器，可以复制后发给朋友。',[{label:'取消'},{label:'保存反馈',primary:true,validate:()=>{if(!$('#feedback-text').value.trim()){toast('请写一点体验反馈。');return false;}return true;},action:v=>{state.feedback.push({text:v.feedback,time:Date.now()});persist();render();toast('已保存反馈。');}}],'<textarea class="field feedback-box" id="feedback-text" name="feedback" maxlength="1200" placeholder="哪里符合预期？哪里不好用？还缺哪些功能？"></textarea>'),
    'export-feedback':()=>{const text=state.feedback.map((f,i)=>`${i+1}. ${f.text}`).join('\n\n')||'暂无反馈。可以先试玩搜索、发布、聊天和模拟订单。';if(navigator.clipboard&&isSecureContext)navigator.clipboard.writeText(text).then(()=>toast('反馈已复制，可以粘贴发给朋友。')).catch(()=>modal('复制反馈','长按下方文字复制。',[{label:'关闭'}],`<textarea class="field" readonly>${esc(text)}</textarea>`));else modal('复制反馈','长按下方文字复制。',[{label:'关闭'}],`<textarea class="field" readonly>${esc(text)}</textarea>`);},
    reset:()=>modal('重置样品记录','将清除本机的模拟订单、消息、发布与反馈，恢复初始演示教材。',[{label:'取消'},{label:'重置样品',primary:true,action:()=>{state=fresh();publishDraft={};persist();tab('home');toast('样品已恢复。');}}]),
  };
  root.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el&&!el.disabled)actions[el.dataset.action]?.(el);});
  window.addEventListener('popstate',event=>{const [view,id]=location.hash.slice(1).split('/');route=event.state?.demoRoute||{view:view||'home',id:id?decodeURIComponent(id):undefined,...(view==='orders'?{side:id==='seller'?'seller':'buyer'}:{})};render();});
  const [initialView,initialId]=location.hash.slice(1).split('/');if(initialView==='orders')route={view:'orders',side:initialId==='seller'?'seller':'buyer'};else if(['home','publish','messages','profile','guide'].includes(initialView))route={view:initialView};else if(initialView==='detail'&&book(initialId))route={view:'detail',id:initialId};
  window.history.replaceState({demoRoute:{...route}},'',location.href);state.checks ||= [];state.feedback ||= [];state.history ||= [];persist();render();
})();
